[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { 
    OPENAI_API_KEY = "",
    VITE_FIREBASE_API_KEY = "",
    VITE_FIREBASE_AUTH_DOMAIN = "",
    VITE_FIREBASE_PROJECT_ID = "",
    VITE_FIREBASE_STORAGE_BUCKET = "",
    VITE_FIREBASE_MESSAGING_SENDER_ID = "",
    VITE_FIREBASE_APP_ID = ""
  }

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
